/**
 * \file testBoard.c
 * \author groupe Larakis
 * \version 1
 * \date 21/03/2016
 * \brief Tests unitaires de Board
 * \details Toutes les fonctions necessaires pour tester board.c
 */

#include <stdlib.h>
#include <stdio.h>

#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>

#include "../src/snake.h"
#include "testSnake.h"

/**
 * \fn testBoardInit
 * \brief Test the bord initilization
 * \details This function test if cells' values are equal to 0 after board's initilization
 * \param state Parameter generated by Cmocka
 */
void testSnakeInit(void **state)
{
    assert_int_equal(1, 1);
}