/**
 * \file testBoard.c
 * \author groupe Larakis
 * \version 1
 * \date 21/03/2016
 * \brief Tests unitaires de Board
 * \details Toutes les fonctions necessaires pour tester board.c
 */

#include <stdlib.h>
#include <stdio.h>

#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>

#include "../src/snake.h"
#include "../src/constants.h"
#include "testSnake.h"


#define SIZE 10
#define ID 2
#define DIR UP
#define TYPE FIRE

Snake s;

void initSnakeTests()
{
    s = snakeCreate(SIZE, ID, DIR, TYPE);
    int i;
	for (i=0; i<snakeGetSize(s); i++)
	{
			snakeUpdateElement(s, i, 15-i, 10);
	}
}

void endSnakeTests()
{
    snakeFree(s);
}

/**
 * \fn testBoardInitPos
 * \brief Test the snake initilization
 * \details This function tests if the snake is nicely posisioned
 * \param state Parameter generated by Cmocka
 */
void testSnakeInitPos(void **state)
{
    initSnakeTests();

    int i;
    for (i = 0; i < snakeGetSize(s); i++)
    {
    	assert_int_equal(snakeGetPos(s, i)->x, 15-i);
    	assert_int_equal(snakeGetPos(s, i)->y, 10);
    }

    endSnakeTests();
}

void testSnakeMovementUp(void **state)
{
	initSnakeTests();

	snakeGoUp(s);

	assert_int_equal(s->head->pos->x, 6);
	assert_int_equal(s->head->pos->y, 9);
	assert_int_equal(s->tail->pos->x, 14);
	assert_int_equal(s->tail->pos->y, 10);

	endSnakeTests();
}


void testSnakeMovementDown(void **state)
{
	initSnakeTests();

	snakeGoDown(s);

	assert_int_equal(s->head->pos->x, 6);
	assert_int_equal(s->head->pos->y, 11);
	assert_int_equal(s->tail->pos->x, 14);
	assert_int_equal(s->tail->pos->y, 10);

	endSnakeTests();
}

void testSnakeMovementLeft(void **state)
{
	initSnakeTests();

	snakeTurnLeft(s);
	assert_int_equal(s->head->pos->x, 5);
	assert_int_equal(s->head->pos->y, 10);
	assert_int_equal(s->tail->pos->x, 14);
	assert_int_equal(s->tail->pos->y, 10);

	endSnakeTests();
}

void testSnakeMovementRight(void **state)
{
	initSnakeTests();

	snakeTurnRight(s);
	assert_int_equal(s->head->pos->x, 7);
	assert_int_equal(s->head->pos->y, 10);
	assert_int_equal(s->tail->pos->x, 14);
	assert_int_equal(s->tail->pos->y, 10);

	endSnakeTests();
}

void testSnakeMovementTp(void **state)
{
	initSnakeTests();

	snakeTeleportation(s, 100, 90);
	assert_int_equal(s->head->pos->x, 100);
	assert_int_equal(s->head->pos->y, 90);
	assert_int_equal(s->tail->pos->x, 14);
	assert_int_equal(s->tail->pos->y, 10);

	endSnakeTests();
}

void testSnakeGrowHead(void **state)
{
	initSnakeTests();

	snakeGrowHead(s);
	assert_int_equal(snakeGetSize(s), SIZE+1);
	assert_int_equal(s->head->pos->x, 6);
	assert_int_equal(s->head->pos->y, 9);
	assert_int_equal(s->tail->pos->x, 15);
	assert_int_equal(s->tail->pos->y, 10);

	endSnakeTests();
}

void testSnakeGrowTail(void **state)
{
	initSnakeTests();

	snakeGrowTail(s);
	assert_int_equal(snakeGetSize(s), SIZE+1);
	assert_int_equal(s->head->pos->x, 6);
	assert_int_equal(s->head->pos->y, 10);
	assert_int_equal(s->tail->pos->x, 15);
	assert_int_equal(s->tail->pos->y, 11);

	endSnakeTests();
}

void testSnakeGetPos(void **state)
{
	initSnakeTests();

	assert_int_equal(snakeGetPos(s, 3)->x, 12);
	assert_int_equal(snakeGetPos(s, 3)->y, 10);

	endSnakeTests();
}

void testSnakeManageDirection(void **state)
{
	initSnakeTests();

	assert_int_equal(snakeGetDirection(s), DIR);
	snakeSetDirection(s, DOWN);
	assert_int_equal(snakeGetDirection(s), UP);
	snakeSetDirection(s, RIGHT);
	assert_int_equal(snakeGetDirection(s), RIGHT);

	endSnakeTests();
}

void testSnakeManageTypes(void **state)
{
	initSnakeTests();

	assert_int_equal(snakeGetType(s), TYPE);
	snakeSetType(s, FIRE);
	assert_int_equal(snakeGetType(s), FIRE);

	endSnakeTests();
}

void testSnakeManageSpeed(void **state)
{
	initSnakeTests();

	assert_int_equal(snakeGetSpeed(s), SNAKE_DEFAULT_SPEED);
	snakeSetSpeed(s, 50);
	assert_int_equal(snakeGetSpeed(s), 50);

	endSnakeTests();
}

void testSnakeManageOrientation(void **state)
{
	initSnakeTests();

	assert_int_equal(snakeElementGetOrientation(s, 2), UP);
	snakeElementSetOrientation(s, 2, RIGHT);
	assert_int_equal(snakeElementGetOrientation(s, 2), RIGHT);

	endSnakeTests();
}

void testSnakeManageControls(void **state)
{	
	initSnakeTests();

	assert_int_equal(snakeGetIsControlReversed(s), 0);
	snakeSetIsControlReversed(s, 1);
	assert_int_equal(snakeGetIsControlReversed(s), 1);

	endSnakeTests();
}

void testSnakeManageCrossBorders(void **state)
{	
	initSnakeTests();

	assert_int_equal(snakeGetCanCrossBorder(s), 0);
	snakeSetCanCrossBorder(s, 1);
	assert_int_equal(snakeGetCanCrossBorder(s), 1);

	endSnakeTests();
}

void testSnakeManageCrossSnakes(void **state)
{	
	initSnakeTests();

	assert_int_equal(snakeGetCanCrossSnake(s), 0);
	snakeSetCanCrossSnake(s, 1);
	assert_int_equal(snakeGetCanCrossSnake(s), 1);

	endSnakeTests();
}

