/**
 * \file testBoard.c
 * \author groupe Larakis
 * \version 1
 * \date 21/03/2016
 * \brief Tests unitaires de Board
 * \details Toutes les fonctions necessaires pour tester board.c
 */

#include <stdlib.h>
#include <stdio.h>

#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>

#include "../src/board.h"
#include "testBoard.h"
#include "../src/enum.h"

#define SIZE_X 32
#define SIZE_Y 16

Board b;

void initTestsBoard()
{
    b = boardInit(SIZE_X, SIZE_Y, 20);
}

void endTestsBoard()
{
    boardFree(b);
}

/**
 * \fn testBoardInit
 * \brief Test the bord initilization
 * \details This function test if cells' values are equal to 0 after board's initilization
 * \param state Parameter generated by Cmocka
 */
void testBoardInit(void **state) 
{
    initTestsBoard();

    int x, y;    
    for(y=0; y<boardGetHeight(b); y++) 
    {
        for (x=0; x<boardGetWidth(b); x++) 
        {
            assert_int_equal(boardGetValue(b, x, y), 0);
        }
    }

    endTestsBoard();
}

/**
 * \fn testBoardValue
 * \brief Test the cell's values' affectation
 * \details The function test if the affectation of the cell (5,8) with the value 3 is correct
 * \param state Parameter generated by Cmocka
 */
void testBoardValue(void **state) 
{
    initTestsBoard();

    boardSetValue(b, 5, 8, 3); // val (5, 8) = 3
    assert_int_equal(boardGetValue(b, 5, 8), 3);

    endTestsBoard();    
}

/**
 * \fn testBoardSize
 * \brief Test the board size
 * \details The function test if the size generated is correct
 * \param state Parameter generated by Cmocka
 */
void testBoardSize(void **state) 
{
    initTestsBoard();

    assert_int_equal(boardGetWidth(b), SIZE_X);
    assert_int_equal(boardGetHeight(b), SIZE_Y);

    endTestsBoard();
}

/**
 * \fn testBoardCopy
 * \brief Test if the board you've just copied is the same
 * \details The function create a new board (by copy), then test different assets, such as size, values, initialization
 * \param state Parameter generated by Cmocka
 */
void testBoardCopy(void **state) 
{
    initTestsBoard();

    Board b2 = boardCopy(b);
    int x,y;
    assert_int_equal(boardGetWidth(b), boardGetWidth(b2));
    assert_int_equal(boardGetHeight(b), boardGetHeight(b2));

    for(y=0; y<boardGetHeight(b); y++) 
    {
        for (x=0; x<boardGetWidth(b); x++) 
        {
            assert_int_equal(boardGetValue(b, x, y), boardGetValue(b2, x, y));
        }
    }
    boardFree(b2);

    endTestsBoard();
}


void testBoardValueAccessor(void **state)
{
    initTestsBoard();

    boardSetValue(b, 5, 7, 15);
    assert_int_equal(boardGetValue(b, 5, 7), 15);

    endTestsBoard();
}

void testBoardInside(void **state)
{
    initTestsBoard();

    assert_int_equal(boardInside(b, 0, 0), 1);
    assert_int_equal(boardInside(b, -1, 0), 0);
    assert_int_equal(boardInside(b, 0, -1), 0);
    assert_int_equal(boardInside(b, SIZE_X-1, SIZE_Y-1), 1);
    assert_int_equal(boardInside(b, SIZE_X, SIZE_Y-1), 0);
    assert_int_equal(boardInside(b, SIZE_X-1, SIZE_Y), 0);

    endTestsBoard();
}

void testManageItem(void **state)
{
    initTestsBoard();

    boardItemAdd(b, 2, 5, 15);
    assert_int_equal(boardGetValue(b, 2, 5), 15);

    boardItemDelete(b, itemSearch(boardGetItemList(b), 2, 5));
    assert_int_equal(boardGetValue(b, 2, 5), 0);

    endTestsBoard();
}

void testManageBoardType(void **state)
{
    initTestsBoard();

    boardSetType(b, 0);
    assert_int_equal(boardGetType(b), 0);

    boardSetType(b, 1);
    assert_int_equal(boardGetType(b), 1);

    endTestsBoard();
}

void testManageAssets(void **state)
{
    initTestsBoard();

    boardSetFieldValue(b, 1, 2, 2);
    assert_int_equal(boardGetFieldValue(b, 1, 2), 2);

    endTestsBoard();
}